baseURL = "/"
languageCode = "en-us"
title = "GNU-my-id"
themesDir = "themes"
theme = "hugo-whisper-theme"

publishDir = "public"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Manual"
    url = "/manual/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/manual'
  homepage_button_text = 'Read The Manual'
  homepage_intro = 'GNU-my-id is a collection of most frequent used cli command.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "GNU-my-id is a collection of most frequent used cli command."
    meta_og_title = "GNU-my-id"
    meta_og_type = "website"
    meta_og_url = "https://GNU-my-id"
    meta_og_image = ""
    meta_og_description = "GNU-my-id is a collection of most frequent used cli command."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ertomedia"
    meta_twitter_creator = "@ertomedia"

  [params.logo]
      mobile = "/images/favicon.svg"
      standard  = "/images/favicon.svg"
